config/routes.rb
Rails.application.routes.draw do
  resources :emails
  devise_for :users
  resources :users
  get 'profile', to: 'users#profile', as: :user_profile

  root 'home#index'

end

app/models/email.rb
class Email < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :mobile_phone, :about_me, :age, :city, :country, :facebook_name, :twitter_name, :skype_name
  validates :mobile_phone, length: { is: 11 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(current_user)
      root_path
  end

end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
  before_action :set_email, only: [:show, :edit, :update, :destroy]

  # GET /emails
  # GET /emails.json
  def index
    @emails = Email.all
  end

  # GET /emails/1
  # GET /emails/1.json
  def show
  end

  # GET /emails/new
  def new
    @email = Email.new
  end

  # GET /emails/1/edit
  def edit
  end

  # POST /emails
  # POST /emails.json
  def create
    @email = Email.new(email_params)

    respond_to do |format|
      if @email.save
        format.html { redirect_to @email, notice: 'Email was successfully created.' }
        format.json { render :show, status: :created, location: @email }
      else
        format.html { render :new }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emails/1
  # PATCH/PUT /emails/1.json
  def update
    respond_to do |format|
      if @email.update(email_params)
        format.html { redirect_to @email, notice: 'Email was successfully updated.' }
        format.json { render :show, status: :ok, location: @email }
      else
        format.html { render :edit }
        format.json { render json: @email.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emails/1
  # DELETE /emails/1.json
  def destroy
    @email.destroy
    respond_to do |format|
      format.html { redirect_to emails_url, notice: 'Email was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_email
      @email = Email.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def email_params
      params.require(:email).permit(:subject)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  # def show
  # end

  # GET /users/new
  # def new
  #   @user = User.new
  # end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  # def create
  #   @user = User.new(user_params)
  #
  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_profile_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def profile
    @user = current_user
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
          # personal info
            :first_name, :last_name, :email, :address, :mobile_phone, :city, :country, :dob, :about_me, :age,
          # social media
            :facebook_name,:twitter_name,:skype_name,
          # ssc education
            :ssc_institution, :ssc_grade, :ssc_passing_year,
          #hse education
            :hse_institution, :hse_grade, :hse_passing_year,
          #degree education
            :degree_institution, :degree_cgpa, :degree_passing_year,
          #skills
            :personal_skills, :pro_skills
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emails_helper.rb
module EmailsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def resource
    @resource ||= User.new
  end

  def resource_name
    :user
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/index.html.slim
.container-fluid
  .w3-sidebar.w3-bar-block.sidebar-style

    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  Inbox
    hr.separator

    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-pencil
          |  Draft
    hr.separator

    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  Sent
    hr.separator

    a.text-color href='#'
      ul.remove-bullet
        li

          span.glyphicon.glyphicon-envelope
          |  Junk
    hr.separator

    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  Trash
    hr.separator

    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  My Folder 1
    hr.separator

    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  My Folder 2
    hr.separator


    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  My Folder 3
    hr.separator


    a.text-color href='#'
      ul.remove-bullet
        li
          span.glyphicon.glyphicon-envelope
          |  My Folder 4
    hr.separator


    .dropup.text-color.side-bar-bottom
      #dropdown-menu-up.dropdown-toggle aria-expanded='false' aria-haspopup='true' data-toggle='dropdown'
        /hr.separator
        span.glyphicon.glyphicon-asterisk.lg-glyphicon.no-padding
          .caret
        span
          span.glyphicon.glyphicon-adjust.lg-glyphicon
          span.md-font 50%
      ul.dropdown-menu aria-labelledby='dropdown-menu-up'
        li
          a href='#'  Compact
        li.divider role='separator'
        li
          a href='#'  Empty
        li.divider role='separator'
        li
          a href='#'  Import messages
        li.divider role='separator'
        li
          a href='#'  Separated link


/! Page Content
.container-fluid
  .body-container
    .w3-container
      h1 My Page
    /img alt="Car" src="img_car.jpg" style="width:100%" /
    .w3-container
      h2 Sidebar Navigation Example
      p The sidebar with is set with "style="width:25%".
      p The left margin of the page content is set to the same value.

app/views/layouts/_alerts_and_notices.html.slim
.container-fluid
  - if flash[:alert] and not flash[:alert].blank?
    .alert.alert-danger.alert-dismissable.fade.in role='alert'
      a.close data-dismiss='alert' &times
      strong= flash[:alert]
  - elsif flash[:notice] and not flash[:notice].blank?
    .alert.alert-success.alert-dismissable.fade.in role='alert'
      a.close data-dismiss='alert' &times
      strong= flash[:notice]
  - elsif flash[:error] and not flash[:error].blank?
    p.error_class
      = flash[:error]

app/views/layouts/_header.html.slim
= render 'layouts/header/topline_navbar'
= render 'layouts/header/navbar'
= render 'layouts/header/navbar_header'

#new-email.modal.fade role='dialog'
  = render 'shared/emails/new_email_modal'

javascript:
  $(document).ready(function () {

    $('.dropdown-submenu a.test').on("click", function (e) {
      $(this).next('ul').toggle();
      e.stopPropagation();
      e.preventDefault();
    });

    $('#show-hide').on('click', function(e){
      if ($('#topline').is(':visible') == true){
        $('#topline').hide();
      }else {
        $('#topline').show();
      }
    });

  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BootstapApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title BootstapApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    link href="https://www.w3schools.com/w3css/4/w3.css" rel="stylesheet"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    = render partial: 'layouts/header'

    div
      = render 'layouts/alerts_and_notices'
      = yield

app/views/layouts/header/_navbar.html.slim
nav.navbar.navbar-inverse.custom-navbar-color
  .container-fluid
    ul.nav.navbar-nav
      li.a
        span
          = link_to((image_tag '/assets/nb_logo_02.png', alt: 'nxb-logo', class: 'img-responsive'), root_path)

    ul.nav.navbar-nav.navbar-right
      li
        a href='#'
          span.glyphicon.glyphicon-envelope
          |  Mail
      li
        a href='#'
          span.glyphicon.glyphicon-user
          |  Address Book
      li
        a
          span.glyphicon.glyphicon-asterisk
          |  Settings
          #show-hide.caret

app/views/layouts/header/_navbar_header.html.slim
nav.navbar.navbar-default.header-bg-color.fix-height
  .container-fluid
    ul.nav.navbar-nav.navbar-left
      li
        a.text-center href='/'
          span.glyphicon.glyphicon-refresh
            br Refresh
      li
        a.text-center*{'data-toggle'=>'modal', 'data-target'=>'#new-email'} href='#'
          span.glyphicon.glyphicon-plus
            br Compose
      li
        a.text-center  href='#'
          span.glyphicon.glyphicon-arrow-left
            br Reply

      li.dropdown
        a.text-center.dropdown-toggle data-toggle='dropdown' href='#'
          span.glyphicon.glyphicon-arrow-left
            br Reply-All
        ul.dropdown-menu
          li
            a href='#' All
          li.divider role='separator'
          li
            a href='#' List
          li.divider role='separator'

      li.dropdown
        a.text-center.dropdown-toggle data-toggle='dropdown'  href='#'
          span.glyphicon.glyphicon-share-alt
            br Forward
        ul.dropdown-menu
          li
            a href='#' Inline
          li.divider role='separator'
          li
            a href='#' with attachment

      li
        a.text-center  href='#'
          span.glyphicon.glyphicon-trash
            br Delete

      li.dropdown
        a.text-center.dropdown-toggle data-toggle='dropdown'
          span.glyphicon.glyphicon-pencil
            br Mark
        ul.dropdown-menu
          li
            a href='#'
              span.glyphicon.glyphicon-star
                | Read
          li.divider role='separator'
          li
            a href='#'
              span.glyphicon.glyphicon-star-empty
                | Unread
          li.divider role='separator'
          li
            a href='#'
              span.glyphicon.glyphicon-flag
                | Flagged
          li.divider role='separator'
          li
            a href='#'
              span.glyphicon.glyphicon-flag
                | Unflagged


      li.dropdown
        a.text-center.dropdown-toggle data-toggle='dropdown' href='#'
          span.glyphicon.glyphicon-option-horizontal
            br More
          ul.dropdown-menu
            li
              a href='#'
                span.glyphicon.glyphicon-print
                  | print this message
            li.divider role='separator'
            li
              a href='#'
                span.glyphicon.glyphicon-download
                  | Download (.eml)
            li.divider role='separator'
            li
              a href='#'
                span.glyphicon.glyphicon-edit
                  | Edit as new
            li.divider role='separator'
            li
              a href='#'
                span.glyphicon.glyphicon-tent
                  | Show source
            li.divider role='separator'


            li.dropdown-submenu
              a.test.dropdown-toggle data-toggle='dropdown' href='#'
                span.glyphicon.glyphicon-move
                | Move to.. &nbsp &nbsp -->

              ul.dropdown-menu
                li
                  a href='#'
                    span.glyphicon.glyphicon-inbox
                    | Inbox
                li.divider role='separator'
                li
                  a href='#'
                    span.glyphicon.glyphicon-new-window
                    | Draft
                li.divider role='separator'
                li
                  a href='#'
                    span.glyphicon.glyphicon-new-window
                    | Sent
                li.divider role='separator'
                li
                  a href='#'
                    span.glyphicon.glyphicon-new-window
                    | Junk
                li.divider role='separator'
                li
                  a href='#'
                    span.glyphicon.glyphicon-new-window
                    | Trash

            li.divider role='separator'
            li
              a href='#'
                span.glyphicon.glyphicon-copy
                  | Copy to..
            li.divider role='separator'
            li
              a href='#'
                span.glyphicon.glyphicon-new-window
                  | Open in new window
            li.divider role='separator'
            li
              a href='#'
                span.glyphicon.glyphicon-filter
                  | create filter


    ul.nav.navbar-nav.navbar-right
      li
        a
          = form_tag '#', method: :get, class: 'form-horizontal form-group has-feedback' do
            .input-group
              span
                = text_field_tag :search, '',  class: 'form-control', placeholder: 'Search..'
              i.form-control-feedback.glyphicon.glyphicon-remove

      li.dropdown
        a.dropdown-toggle data-toggle='dropdown'
          button.btn.btn-default.btn-horizontal
            span
              | All
        ul.dropdown-menu
          li
            a
              span.text-center.glyphicon.glyphicon-inbox
                | Unread
          li
            a
              span.text-center.glyphicon.glyphicon-inbox
                | Flagged
          li
            a
              span.text-center.glyphicon.glyphicon-inbox
                | Unanswered
          li
            a
              span.text-center.glyphicon.glyphicon-inbox
                | Priority

app/views/layouts/header/_topline_navbar.html.slim
nav.navbar-xs.navbar-inverse#topline
  .container-fluid
    ul.nav.navbar-nav
      li
        a.span
          | About
    ul.nav.navbar-nav.navbar-right
      - if current_user.present?
        li
          a
            span.email-color =current_user.email
        li
          a*{'data-method'=>:delete} href=destroy_user_session_path
            span.glyphicon.glyphicon-off
            |  Logout
      - else
        li
          a*{'data-toggle'=> 'modal', 'data-target'=>'#login-form'} href='#'
            span.glyphicon.glyphicon-off
            |  Login


#login-form.modal.fade role='dialog'
  = render 'users/sign_in_modal'

app/views/users/_form.html.slim
h5 Please complete your profile first to preview it.
= simple_form_for(@user, html: {class: 'horizontal-form well well-lg'}) do |f|

  .row
    h4.text-center Personal information
  .profile-section
    .row
      .col-xs-6
        .alert.alert-info
          = f.input :first_name, autofocus: true, error: 'Last name should not be blank'
          = f.input :last_name, error: 'Last name should not be blank'
          = f.input :email, required: true, error: 'Email cannot be blank!'
          = f.input :mobile_phone, required: true, hint: 'It should be 11 digits', warning: 'Mobile number should be 11 digits '
          = f.input :about_me, required: true
      .col-xs-6
        .alert.alert-info
          = f.input :city, placeholder: 'Add your current city'
          = f.input :country
          = f.input :dob
          = f.input :age, required: true, hint: 'Age should be the whole number'

  .row
    h4.text-center Educational Information
  .profile-section
    .row
      .col-xs-6
        h5.text-center Secondary School Certificate
        .alert.alert-success
          = f.input :ssc_institution, label: 'Institution Name'
          = f.input :ssc_grade, label: 'Grade'
          = f.input :ssc_passing_year, label: 'Passing Year'
      .col-xs-6
        h5.text-center Higher School Examination
        .alert.alert-success
          = f.input :hse_institution, label: 'Institution Name'
          = f.input :hse_grade, label: 'Grade'
          = f.input :hse_passing_year, label: 'Passing Year'
    .row
      .col-xs-6
        h5.text-center Degree
        .alert.alert-success
          = f.input :degree_institution, label: 'Institution Name'
          = f.input :degree_cgpa, label: 'CGPA'
          = f.input :degree_passing_year, label: 'Passing Year'

  .row
    h4.text-center Social Media
  .profile-section
    .row
      .col-xs-6
        .alert.alert-warning
          = f.input :skype_name
          = f.input :facebook_name
      .col-xs-6
        .alert.alert-warning
          = f.input :twitter_name

  .row.button-container
    .actions
      = f.button :submit, class: 'btn btn-primary'
      |&nbsp
      = link_to 'Cancel', users_path, class: 'btn btn-default'

app/views/users/_sign_in_modal.html.slim
.modal-dialog.modal-sm
  .modal-content
    .modal-header
      button.close data-dismiss='modal' type='button' &times;
      h3.modal-title.text-center Log in

    = simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
      .modal-body
        .container-fluid
          .row
            .col-md-12
              = f.input :email, required: false, autofocus: true
              = f.input :password, required: false
              = f.input :remember_me, as: :boolean if devise_mapping.rememberable?
      .modal-footer
        = f.button :submit, 'Login'

app/views/users/edit.html.slim
.container-fluid
  = render 'form'

app/views/users/index.html.slim
h1 Listing Users
table
  thead
    tr
      th First name
      th Last name
      th Email
      th colspan="3" 
  tbody
    - @users.each do |user|
      tr
        td = user.first_name
        td = user.last_name
        td = user.email
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, method: :delete, data: {confirm: 'Are you sure?'}

br
/= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 New User

= render 'form'

= link_to 'Back', users_path

app/views/users/profile.html.slim
.container-fluid
  .well.well-lg
    .profile-section

      .row
        .col-sm-4.col-md-3.col-lg-2
          /= link_to (image_tag '/assets/profile-pic.jpg', alt: 'path was changed.', size: '160x160', class: 'img-circle left-block')
          /| #{@user.first_name} #{@user.last_name}
          /| Johar Town, Lahore

          = image_tag '/assets/profile-pic.jpg', alt: 'path was changed.', class: 'center-block img-responsive img-circle left-block'
        .col-sm-8.col-md-9.col-lg-10
          p #{@user.first_name} #{@user.last_name}
          p Location: Lahore

      ul.nav.nav-tabs
        li.active
          a data-toggle='tab' href='#basic' Basic
        li
          a data-toggle='tab' href='#education' Education
        li
          a data-toggle='tab' href='#skills' Skills
        li
          a data-toggle='tab' href='#social-media' Social Media

      .tab-content
        #basic.tab-pane.fade.in.active
          .container-fluid
            row
              h3.text-center Personal Information

            .row
              .col-xs-6
                label Email:
                = @user.email

              .col-xs-6
                label Age:
                = @user.age
            .row
              .col-xs-6
                label for='Mobile' Mobile:
                = @user.mobile_phone

            .row
              .col-xs-12
                label About:
                = @user.about_me

        #education.tab-pane.fade
          .container-fluid
            .row
              h3.text-center Educational Information

            .row
              .col-xs-12
                h4.text-left Secondary School Information

            .row
              .col-xs-12
                label Institution Name:
                = @user.ssc_institution
              .col-xs-12
                label Year of Passing:
                = @user.ssc_passing_year
              .col-xs-12
                label Grade:
                = @user.ssc_grade

            .row
              .col-xs-12
                h4.text-left Higher Secondary Examination

            .row
              .col-xs-12
                label Institution Name:
                = @user.hse_institution
              .col-xs-12
                label Year of Passing:
                = @user.hse_passing_year
              .col-xs-12
                label Grade:
                = @user.hse_grade

            .row
              .col-xs-12
                h4.text-left Degree

            .row
              .col-xs-12
                label Institution Name:
                = @user.degree_institution
              .col-xs-12
                label Year of Passing:
                = @user.degree_passing_year
              .col-xs-12
                label Grade:
                = @user.degree_cgpa

        #skills.tab-pane.fade
          .container-fluid
            .row
              h3.text-center Skills

            .row
              .col-xs-6
                h4
                  label Personal Skills
                ul
                  li Hard working
                  li Tolerant
                  li Polite

              .col-xs-6
                h4
                  label Professional Skills
                  ul
                    li Good Communication
                    li Team Player
                    li Influencing

        #social-media.tab-pane.fade
          .container-fluid
            .row
              h3.text-center Social Media

            .row
              .col-xs-6
                label Skype:
                = @user.skype_name
              .col-xs-6
                label Facebook:
                = @user.facebook_name

            .row
              .col-xs-12
                label Twitter:
                = @user.twitter_name

    .container-fluid
      = link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-default'

    /.row
    /  .col-md-6
    /    h4
    /      label Professional Skills


/  | Country:
/  strong= @user.country
/  br
/
/  | About Me:
/  strong= @user.about_me
/
/  br
/  br
/
/
/.container
/  h4 Educational Information
/
/  h5 SSC Info
/  | Institution Name:
/  strong= @user.ssc_institution
/  br
/
/  | Grade:
/  strong= @user.ssc_grade
/  br
/
/  | Passing Year:
/  strong= @user.ssc_passing_year
/  br
/
/  h5 HSE Info
/  | Institution Name:
/  strong= @user.ssc_institution
/  br
/
/  | Grade:
/  strong= @user.ssc_grade
/  br
/
/  | Passing Year:
/  strong= @user.ssc_passing_year
/  br
/
/  h5 Degree Info
/  | Institution Name:
/  strong= @user.ssc_institution
/  br
/
/  | Grade:
/  strong= @user.ssc_grade
/  br
/
/  | Passing Year:
/  strong= @user.ssc_passing_year
/  br
/  br
/
/  /h3 HSE
/  /| Institution Name:
/  /strong= @user.hse_institution
/  /br
/  /
/  /h3 Degree
/  /| Institution Name:
/  /strong= @user.degree_institution
/  /br
/
/.container
/  h4 Social Media
/
/  | Skype Name:
/  strong= @user.skype_name
/  br
/
/  | Facebook Name:
/  strong= @user.facebook_name
/  br
/
/  | Twitter Name:
/  strong= @user.twitter_name

app/views/users/show.html.slim
/p#notice = notice
/.container
/     table.table.table-condensed
/        thead
/            tr
/                th First name
/                th Last name
/                th Email
/        tbody
/            tr
/            td = @user.first_name
/            td = @user.last_name
/            td = @user.email
/= link_to 'Edit', edit_user_path(@user)
/= link_to 'Back', users_path